model_name_dict = {
    #random forest
    "sklearn_rf_390014_24": "RandomForest_a",
    "sklearn_rf_390014_25": "RandomForest_b",
    "sklearn_rf_390014_97": "RandomForest_c",
    "sklearn_rf_390014_96": "RandomForest_d",
    "sklearn_rf_390014_14": "RandomForest_e",
    "sklearn_rf_390014_12": "RandomForest_f",
    "sklearn_rf_390014_13": "RandomForest_g",
    "sklearn_rf_390014_72": "RandomForest_h",
    
    "sklearn_rf_392335_24": "RandomForest_a",
    "sklearn_rf_392335_25": "RandomForest_b",
    "sklearn_rf_392335_97": "RandomForest_c",
    "sklearn_rf_392335_96": "RandomForest_d",
    "sklearn_rf_392335_14": "RandomForest_e",
    "sklearn_rf_392335_12": "RandomForest_f",
    "sklearn_rf_392335_13": "RandomForest_g",
    "sklearn_rf_392335_72": "RandomForest_h",
    #dnn
    "single_regression_2": "SingleRegression_a",
    "single_regression_11": "SingleRegression_b",
    "single_classification_22": "SingleClassification_a",
    "single_classification_42": "SingleClassification_b",
    "multi_classification_15": "MultiClassification_a",
    "multi_classification_18": "MultiClassification_b",
    "vanilla_lstm_8": "LSTM_a",
    "vanilla_lstm_19": "LSTM_b",
    #irv
    "deepchem_irv_5": "IRV_a",
    "deepchem_irv_10": "IRV_b",
    "deepchem_irv_20": "IRV_c",
    "deepchem_irv_40": "IRV_d",
    "deepchem_irv_80": "IRV_e",
    #docking
    "dockscore_hybrid": "Docking_hybrid",
    "dockscore_fred": "Docking_fred",
    "dockscore_dock6": "Docking_dock6",
    "dockscore_rdockint": "Docking_rdockint",
    "dockscore_rdocktot": "Docking_rdocktot",
    "dockscore_surflex": "Docking_surflex",
    "dockscore_ad4": "Docking_ad4",
    "dockscore_plants": "Docking_plants",
    "dockscore_smina": "Docking_smina",
    "consensus_dockscore_max": "ConsensusDocking_max",
    "consensus_bcs_efr1_opt": "ConsensusDocking_efr1_opt",
    "consensus_bcs_rocauc_opt": "ConsensusDocking_rocauc_opt",
    "consensus_dockscore_median": "ConsensusDocking_median",
    "consensus_dockscore_mean": "ConsensusDocking_mean",
    #baseline
    "baseline": "baseline"
}
