model_name_dict = {
    #lightchemPRAUC_1Layer1Model
    "PRAUC_5Layer1Model": "LightChem_a",
    "PRAUC_10Layer1Model": "LightChem_b",
    "ROCAUC_5Layer1Model": "LightChem_c",
    "ROCAUC_10Layer1Model": "LightChem_d",
    "ROCAUC_1Layer1Model": "LightChem_e",
    "PRAUC_1Layer1Model": "LightChem_f",
    #random forest
    "sklearn_rf_390014_24": "RandomForest_a",
    "sklearn_rf_390014_25": "RandomForest_b",
    "sklearn_rf_390014_97": "RandomForest_c",
    "sklearn_rf_390014_96": "RandomForest_d",
    "sklearn_rf_390014_14": "RandomForest_e",
    "sklearn_rf_390014_12": "RandomForest_f",
    "sklearn_rf_390014_13": "RandomForest_g",
    "sklearn_rf_390014_72": "RandomForest_h",
    #dnn
    "single_regression_2": "SingleRegression_a",
    "single_regression_11": "SingleRegression_b",
    "single_classification_22": "SingleClassification_a",
    "single_classification_42": "SingleClassification_b",
    "multi_classification_15": "MultiClassification_a",
    "multi_classification_18": "MultiClassification_b",
    "vanilla_lstm_8": "LSTM_a",
    "vanilla_lstm_19": "LSTM_b",
    #irv
    "deepchem_irv_5": "IRV_a",
    "deepchem_irv_10": "IRV_b",
    "deepchem_irv_20": "IRV_c",
    "deepchem_irv_40": "IRV_d",
    "deepchem_irv_80": "IRV_e",
    #docking
    "dockscore_hybrid": "Docing_hybrid",
    "dockscore_fred": "Docing_fred",
    "dockscore_dock6": "Docing_dock6",
    "dockscore_rdockint": "Docing_rdockint",
    "dockscore_rdocktot": "Docing_rdocktot",
    "dockscore_surflex": "Docing_surflex",
    "dockscore_ad4": "Docing_ad4",
    "dockscore_plants": "Docing_plants",
    "dockscore_smina": "Docing_smina",
    "consensus_dockscore_max": "ConsensusDocing_max",
    "consensus_bcs_efr1_opt": "ConsensusDocing_efr1_opt",
    "consensus_bcs_rocauc_opt": "ConsensusDocing_rocauc_opt",
    "consensus_dockscore_median": "ConsensusDocing_median",
    "consensus_dockscore_mean": "ConsensusDocing_mean",
}
