file_paths_dict = {
    'Keck_Pria_AS_Retest': {
        0: 'single_classification_22/45540945/',
        1: 'single_classification_42/45539118/',
        2: 'single_regression_2/45540957/',
        3: 'single_regression_11/45540958/',
        4: 'vanilla_lstm_8/46352274/',
        5: 'vanilla_lstm_19/46495805/',
        6: 'multi_classification_15/eval_keck/',
        7: 'multi_classification_18/eval_keck/',
        8: 'random_forest_12/',
        9: 'random_forest_13/',
        10: 'random_forest_14/',
        11: 'random_forest_24/',
        12: 'random_forest_25/',
        13: 'random_forest_25/',
        14: 'random_forest_96/',
        15: 'random_forest_97/',
        16: 'irv_5/',
        17: 'irv_10/',
        18: 'irv_20/',
        19: 'irv_40/',
        20: 'irv_80/',
        21: 'dockscore_hybrid/',
        22: 'dockscore_fred/',
        23: 'dockscore_dock6/',
        24: 'dockscore_rdockint/',
        25: 'dockscore_rdocktot/',
        26: 'dockscore_surflex/',
        27: 'dockscore_ad4/',
        28: 'dockscore_plants/',
        29: 'dockscore_smina/',
        30: 'consensus_dockscore_max/',
        31: 'consensus_bcs_efr1_opt/',
        32: 'consensus_bcs_rocauc_opt/',
        33: 'consensus_dockscore_median/',
        34: 'consensus_dockscore_mean/',
        35: 'baseline/'
    },
    'Keck_Pria_FP': {
        0: 'single_classification_22/45710870/',
        1: 'single_classification_42/45710871/',
        2: 'single_regression_2/45710874/',
        3: 'single_regression_11/45710875/',
        4: 'vanilla_lstm_8/46547695/',
        5: 'vanilla_lstm_19/46547696/',
        6: 'multi_classification_15/eval_keck/',
        7: 'multi_classification_18/eval_keck/',
        8: 'random_forest_12/',
        9: 'random_forest_13/',
        10: 'random_forest_14/',
        11: 'random_forest_24/',
        12: 'random_forest_25/',
        13: 'random_forest_25/',
        14: 'random_forest_96/',
        15: 'random_forest_97/',
        16: 'irv_5/',
        17: 'irv_10/',
        18: 'irv_20/',
        19: 'irv_40/',
        20: 'irv_80/',
        21: 'dockscore_hybrid/',
        22: 'dockscore_fred/',
        23: 'dockscore_dock6/',
        24: 'dockscore_rdockint/',
        25: 'dockscore_rdocktot/',
        26: 'dockscore_surflex/',
        27: 'dockscore_ad4/',
        28: 'dockscore_plants/',
        29: 'dockscore_smina/',
        30: 'consensus_dockscore_max/',
        31: 'consensus_bcs_efr1_opt/',
        32: 'consensus_bcs_rocauc_opt/',
        33: 'consensus_dockscore_median/',
        34: 'consensus_dockscore_mean/'
    },
    'Keck_RMI': {
        0: 'single_classification_22/46244865/',
        1: 'single_classification_42/46101892/',
        2: 'single_regression_2/46245031/',
        3: 'single_regression_11/46245032/',
        4: 'vanilla_lstm_8/46680983/',
        5: 'vanilla_lstm_19/46680994/',
        6: 'multi_classification_15/eval_keck/',
        7: 'multi_classification_18/eval_keck/',
        8: 'random_forest_12/',
        9: 'random_forest_13/',
        10: 'random_forest_14/',
        11: 'random_forest_24/',
        12: 'random_forest_25/',
        13: 'random_forest_25/',
        14: 'random_forest_96/',
        15: 'random_forest_97/',
        16: 'irv_5/',
        17: 'irv_10/',
        18: 'irv_20/',
        19: 'irv_40/',
        20: 'irv_80/',
        21: 'dockscore_hybrid/',
        22: 'dockscore_fred/',
        23: 'dockscore_dock6/',
        24: 'dockscore_rdockint/',
        25: 'dockscore_rdocktot/',
        26: 'dockscore_surflex/',
        27: 'dockscore_ad4/',
        28: 'dockscore_plants/',
        29: 'dockscore_smina/',
        30: 'consensus_dockscore_max/',
        31: 'consensus_bcs_efr1_opt/',
        32: 'consensus_bcs_rocauc_opt/',
        33: 'consensus_dockscore_median/',
        34: 'consensus_dockscore_mean/'
    }
}

model_list = [
    'single_classification_a', 'single_classification_b',
    'single_regression_a', 'single_regression_b',
    'vanilla_lstm_a', 'vanilla_lstm_b',
    'multi_classification_a', 'multi_classification_b',
    'random_forest_a', 'random_forest_b', 'random_forest_c', 'random_forest_d',
    'random_forest_e', 'random_forest_f', 'random_forest_g', 'random_forest_h',
    'irv_a', 'irv_b', 'irv_c', 'irv_d', 'irv_e',
    'dockscore_hybrid',
    'dockscore_fred',
    'dockscore_dock6',
    'dockscore_rdockint',
    'dockscore_rdocktot',
    'dockscore_surflex',
    'dockscore_ad4',
    'dockscore_plants',
    'dockscore_smina',
    'consensus_dockscore_max',
    'consensus_bcs_efr1_opt',
    'consensus_bcs_rocauc_opt',
    'consensus_dockscore_median',
    'consensus_dockscore_mean', 
    'baseline'
]
